config/routes.rb
# frozen_string_literal: true

HyraxArchivematica::Engine.routes.draw do
  # Generic work routes
  resources :works, only: [] do
    member do
      resources :archives, as: :work_archives, only: [:index, :new]
    end
  end
end

app/models/concerns/hyrax_archivematica/archive_record_behaviour.rb
module HyraxArchivematica
  module ArchiveRecordBehaviour
    extend ActiveSupport::Concern

    def calculate_md5(file,chunk=4096)
      # Digest::MD5.hexdigest(File.read(file))
      # dontnakaballsiyit
      md5 = Digest::MD5.new
      buf = ""
      file = File.new(file)
      while buf = file.read(chunk)
        md5.update(buf)
      end
      md5.hexdigest
    end

    def archive_records(work_id) # Could become unwieldy?
      ArchiveRecord.where(work_id:work_id).order(created_at: :desc)
    end

    # return the latest archive record that does not have a transfer_uuid
    # so we can assume has not gotten to the ArchivematicaTransferJob and has no transfer_uuid
    def not_started_archive_records(work_id)
      ArchiveRecord.where(work_id:work_id, transfer_uuid: nil).order(created_at: :desc)
    end
    
    # return the latest archive record that does not have a transfer_uuid
    # so we can assume has not gotten to the ArchivematicaTransferJob and has no transfer_uuid
    def active_archive_records(work_id)
      ArchiveRecord.where(work_id:work_id).where.not(archive_status: HyraxArchivematica::Constants::STATUS_ARCHIVE_COMPLETE).order(created_at: :desc)
    end

    # returns the latest archive_Record that has the given file_set_id
    # only for use when we don't have access to the work id and need to get this from the AR
    # i.e. triggered by a file that has been deleted so is no longer associated with the parent work
    # The `all` is ugly as hell
    def latest_archive_record_by_file_set_id(file_set_id)
      ArchiveRecord.all.order(created_at: :desc).select { |ar| ar.file_set_ids.include? file_set_id }.first
    end
    
    def bag_path
      @archive_record.bag_path
    end

    def bag_zip
      File.basename(bag_path)
    end

    def bag_hash
      @archive_record.bag_hash
    end

    #TODO find a suitable home for this stuff
    def am_host
      HyraxArchivematica.am_host
    end

    def am_user
      HyraxArchivematica.am_user
    end

    def am_ssh_key
      HyraxArchivematica.am_ssh_key
    end

    def am_ssh_user
      HyraxArchivematica.am_ssh_user
    end

    def am_transfer_source_dir
      HyraxArchivematica.am_transfer_source_dir
    end

    def bagit_export_path
      HyraxArchivematica.bagit_export_path
    end
  
    def transfer_path
      HyraxArchivematica.transfer_path
    end
   
    def transfer_work_path(work_id)
      File.join(transfer_path,work_id.to_s)
    end
  
  end
end

app/models/hyrax_archivematica/archive_record.rb
module HyraxArchivematica
  class ArchiveRecord < ApplicationRecord
    serialize :file_set_ids, Array

  end
end

app/controllers/hyrax_archivematica/application_controller.rb
# frozen_string_literal: true

module HyraxArchivematica
  class ApplicationController < ::ApplicationController
    helper Rails.application.class.helpers
    protect_from_forgery with: :exception
  end
end

app/controllers/hyrax_archivematica/archives_controller.rb
# frozen_string_literal: true

require_dependency "hyrax_archivematica/application_controller"

module HyraxArchivematica
  class ArchivesController < ApplicationController
    include Hyrax::ThemedLayoutController
    include HyraxArchivematica::ArchiveRecordBehaviour
    before_action :authenticate_user!
#    before_action :set_exporter, only: [:show, :edit, :update, :destroy]
    with_themed_layout 'dashboard'

    # Catch permission errors
    # TODO: Isn't this already handled?
    rescue_from CanCan::AccessDenied do |exception|
      if current_user&.persisted?
        redirect_to root_url, alert: exception.message
      else
        session["user_return_to"] = request.url
        redirect_to main_app.new_user_session_url, alert: exception.message
      end
    end

    def new
      HyraxArchivematica::ArchiveWorkflowManager.new(params: {user: current_user, work_id: params[:id], force: true})
      redirect_to hyrax_archivematica.work_archives_path, notice: "New archive process started"
    end

    def create
      @proxy_deposit_request.sending_user = current_user
      if @proxy_deposit_request.save
        redirect_to hyrax.archives_path, notice: "Archive job created"
      else
        @work = Hyrax::WorkRelation.new.find(params[:id])
        render :new
      end
    end

    def index
      @archive_records = archive_records(params[:id])
      @work = Hyrax::WorkRelation.new.find(params[:id])
      add_breadcrumb t(:'hyrax.controls.home'), main_app.root_path
      add_breadcrumb t(:'hyrax.dashboard.breadcrumbs.admin'), hyrax.dashboard_path
      add_breadcrumb @work.to_s, main_app.polymorphic_path(@work) 
      add_breadcrumb t(:'hyrax_archivematica.dashboard.work.archives'), hyrax_archivematica.work_archives_path
    end

    private

    def authorize_depositor_by_id
      @id = params[:id]
      authorize! :archive, @id
      @archive_record.work_id = @id
    rescue CanCan::AccessDenied
      redirect_to root_url, alert: 'You are not authorized to archive this work.'
    end

    def load_archive_record
      @archive_record = ArchiveRecord.new(archive_record_params)
    end

    def archive_record_params
      params.require(:id)
    end

  end
end

app/helpers/hyrax_archivematica/archive_record_helper.rb
module HyraxArchivematica
  module ArchiveRecordHelper
    def aip_url(archive_record)
      return nil unless archive_record.ingest_uuid.present?
      link_to archive_record.ingest_uuid, "#{HyraxArchivematica.am_protocol}://#{HyraxArchivematica.am_host}/archival-storage/#{archive_record.ingest_uuid}/", :target => "_blank"
    end
  end
end

app/views/hyrax/my/_work_action_menu.html.erb
<% ul_id = 'admin-set-action-dropdown-ul-' + document.id %>

<div class="btn-group">

  <button class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" type="button" id="dropdownMenu_<%= document.id %>" aria-haspopup="true" aria-expanded="false" aria-controls="<%= ul_id %>">
    <span class="sr-only"><%= t("hyrax.dashboard.my.sr.press_to") %> </span>
    <%= t("hyrax.dashboard.my.action.select") %>
    <span class="caret" aria-hidden="true"></span>
  </button>

  <ul role="menu" id="<%= ul_id %>" class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu_<%= document.id %>">

    <% if can? :edit, document.id %>
      <li role="menuitem" tabindex="-1">
        <%= link_to [main_app, :edit, document] do %>
          <i class="glyphicon glyphicon-pencil" aria-hidden="true"></i>
          <span> <%= t("hyrax.dashboard.my.action.edit_work") %> </span>
        <% end %>
      </li>

      <li role="menuitem" tabindex="-1">
        <%= link_to [main_app, document],
                    method: :delete,
                    data: {
                      confirm: t("hyrax.dashboard.my.action.work_confirmation", application_name: application_name) } do %>
          <i class="glyphicon glyphicon-trash" aria-hidden="true"></i>
          <span> <%= t("hyrax.dashboard.my.action.delete_work") %> </span>
        <% end %>
      </li>
    <% end %>

    <li role="menuitem" tabindex="-1">
      <%= display_trophy_link(current_user, document.id) do |text| %>
        <i class="glyphicon glyphicon-star" aria-hidden="true"></i> <%= text %>
      <% end %>
    </li>

    <% if can? :transfer, document.id %>
      <li role="menuitem" tabindex="-1">
        <%= link_to(hyrax.new_work_transfer_path(document.id), class: 'itemicon itemtransfer', title: t("hyrax.dashboard.my.action.transfer")) do %>
          <i class="glyphicon glyphicon-transfer" aria-hidden="true"></i>
          <span> <%= t("hyrax.dashboard.my.action.transfer") %> </span>
        <% end %>
      </li>
    <% end %>

    <% if can? :archive, document.id %>
      <li role="menuitem" tabindex="-1">
        <%= link_to(hyrax_archivematica.work_archives_path(document.id), class: 'itemicon itemarchive', title: t("hyrax.dashboard.my.action.archive")) do %>
          <i class="glyphicon glyphicon-lock" aria-hidden="true"></i>
          <span> <%= t("hyrax.dashboard.my.action.archive") %> </span>
        <% end %>
      </li>
    <% end %>

  </ul>
</div>

app/views/hyrax_archivematica/archives/index.html.erb
<% provide :page_header do %>
  <h1><span class="fa fa-archive" aria-hidden="true"></span> <%= t('hyrax_archivematica.dashboard.work.title')%> <%= @work[:title].first %></h1>
  <div class="pull-right">
    <%= link_to new_work_archive_path, class: 'btn btn-primary' do %>
      <span class="fa fa-lock" aria-hidden="true"></span> <%= t(:'helpers.action.archive.archive_item') %>
    <% end %>
  </div>
<% end %>


<div class="panel panel-default">
  <div class="panel-body">
    <% if @archive_records.present? %>
      <div class="table-responsive">
        <table class="table table-striped datatable">
          <thead>
            <tr>
              <th scope="col"><%= t('hyrax_archivematica.id') %></th>
              <td scope="col" class="nosort"></td>
              <th scope="col"><%= t('hyrax_archivematica.status') %></th>
              <th scope="col"><%= t('hyrax_archivematica.created') %></th>
              <th scope="col"><%= t('hyrax_archivematica.updated') %></th>
              <th scope="col"><%= t('hyrax_archivematica.files') %></th>
              <th scope="col"><%= t('hyrax_archivematica.files_checksum') %></th>
              <th scope="col"><%= t('hyrax_archivematica.metadata_checksum') %></th>
              <th scope="col"><%= t('hyrax_archivematica.transfer_uuid') %></th>
              <th scope="col"><%= t('hyrax_archivematica.ingest_uuid') %></th>
            </tr>
          </thead>
          <tbody>
            <% @archive_records.each do |archive_record| %>
              <tr>
                <th scope="row"><%= archive_record.id %></th>
                <td class="ha <%= "ha_#{archive_record.archive_status}" %>"><span class="fa fa-lock" aria-hidden="true"></span></td>
                <td class="ha <%= "ha_#{archive_record.archive_status}" %>"><%= t("hyrax_archivematica.#{archive_record.archive_status}") %></td>
                <td><%= archive_record.created_at %></td>
                <td><%= archive_record.updated_at %></td>
                <td><%= archive_record.file_set_ids %></td>
                <td><%= archive_record.files_hash.truncate(16) %></td>
                <td><%= archive_record.metadata_hash.truncate(16) %></td>
                <td><%= archive_record.transfer_uuid %></td>
                <td><%= aip_url archive_record %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <% else %>
        <p>No archives of this work have been created.</p>
      <% end %>
  </div>
</div>

<script>
$(document).ready(function() {
    $('.datatable').DataTable({
      destroy: true,
      'columnDefs': [
          { 'orderable': false, 'targets': [1, 5, 6, 7, 8, 9] }
      ],
      'language': {
        'info': 'Showing _START_ to _END_ of _TOTAL_ archive records',
        'infoEmpty': 'No archive records to show',
        'infoFiltered': '(filtered from _MAX_ total archive records)',
        'lengthMenu': 'Show _MENU_ archive records'
      }
    })
  })
</script>

app/views/hyrax_archivematica/archives/new.html.erb
<% provide :page_header do %>
  <h1><span class="fa fa-edit" aria-hidden="true"></span> New Archive</h1>
<% end %>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default tabs">
      <%#= simple_form_for @exporter do |form| %>
        <%#= render 'form', exporter: @exporter, form: form %>
        <div class="panel-footer">
          <div class='pull-right'>
            <%#= form.button :submit, value: 'Create and Export', class: 'btn btn-primary' %>
            |
            <%#= form.button :submit, value: 'Create', class: 'btn btn-primary' %>
            |
            <%# cancel_path = form.object.persisted? ? exporter_path(form.object) : exporters_path %>
            <%#= link_to t('.cancel'), cancel_path, class: 'btn btn-default ' %>
          </div>
        </div>
      <%# end %>
    </div>
  </div>
</div>